### ISSUE TITLE
Motion Based Stopping Criteria

### ISSUE THREAD

**Issue by agupta231** [WPI-MMR/gym_solo#21]
Implementation of #19.

From the most basic RL testing, it seems as if the model pretty quickly just ends up on the ground twitching. Obviously, once it's in this state, it can be very difficult to get out of. Figure that it could be interesting to track the derivative of position over time and terminate the episode when it approaches 0.

**Comment by mahajanrevant** [comment]
I agree with this so I am removing the question label

**Comment by agupta231** [comment]
I am glad that you agree with the consensus

**Comment by agupta231** [comment]
Don't think that this is actually necessary. We would kind of want it to be stable, as that would maximize the reward. The standard in the field is just to terminate an episode after `T` timesteps, and we can just optimize `T`.

Closing unless there's a reason to reopen it.
