### ISSUE TITLE
Create Motor Encoder Observation for Solo 8 v2 Vanilla

### ISSUE THREAD

**Issue by agupta231** [WPI-MMR/gym_solo#4]
Need to implement a `gym_solo.core.obs.Observation` that will return the motor encoder values for the Solo8v2 Vanilla model (already implemented in the environment).

At the very least, these should return the position of the motor encoders (labelled for each joint name, of course). According to the [documentation](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.p3s2oveabizm), it seems that we can get the position, velocity, and applied angular forces on all of joints. 

I'm not really sure if we need the velocity / applied angular forces in the observation-- @andrew103  or @mahajanrevant could one of you pitch in and give some insight to what will be realistic in terms of the robot? Worst comes to worst, we can add those as another observation cause I think that information could be useful in the RL aspect of the project.

**Comment by mahajanrevant** [comment]
I think we should just stick with the position for now. I don't really see the need for the other two right now

**Comment by agupta231** [comment]
For [getting the the joint states](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.p3s2oveabizm). 

Get the [number of joints](https://github.com/WPI-MMR/simulation_playground/blob/master/pybullet/noros/interactive.py#L40).

Getting the [joint names](https://github.com/WPI-MMR/simulation_playground/blob/master/pybullet/noros/interactive.py#L48).
