### ISSUE TITLE
Create Rewards Factory

### ISSUE THREAD

**Issue by agupta231** [WPI-MMR/gym_solo#5]
Similar to the observation factory. The reward factory should be able to take in `Reward` objects, similar to an `Observation` object, evaluate the rewards for the state, and combine them.

I'm thinking of making the final reward a linear combination of the registered rewards. With that in mind, consider the following example:

```python
r1 = Reward()
r2 = Reward()
r3 = Reward()

rf = RewardFactory()

r1.register_reward(-1, r1) 
r1.register_reward(.1, r2)
r1.register_reward(.9, r3)
```

Notice that `register_reward()` has two args: `weight: float` and `reward: gym_solo.core.rewards.Reward`. Thus, the final reward would evaluate to: `-r1() + 0.1 * r2() + 0.9 * r3()`. Figure that if you need functionality more elaborate than a linear combination, you should be offloading that processing into a `Reward` class.

@mahajanrevant thoughts on this? lmk if you think we need anything stronger than linear combinations in the `RewardFactory`.

**Comment by agupta231** [comment]
Will also need integrate the reward factory with the solo `gym.Env` + tests.

**Comment by mahajanrevant** [comment]
In long term, it makes sense to have this to be able to experiment with multiple different types of rewards. From the implementation you showed me, it looks simple enough so I am good with it
